const NFTS__ACTIONS = {
    _INITIAL_GET_NFT_DATA: '_INITIAL_GET_NFT_DATA',
    _SUCESS_GET_NFT_DATA: '_SUCESS_GET_NFT_DATA',
    _FAILURE_GET_NFT_DATA: '_FAILURE_GET_NFT_DATA',
    _SET_LIMIT_NFT: '_SET_LIMIT_NFT',
    _SET_QUERY_NFT: '_SET_QUERY_NFT',
    _SET_CHAIN_NFT: '_SET_CHAIN_NFT',
    _SET_FILTER_NFT: '_SET_FILTER_NFT',
}


export default NFTS__ACTIONS;